# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCNpVQVFcAeCCpMwWSIPf44MH9Kxqyho

#**integrantes**
1.   *Juan Eduardo Ardila Garzón*
2.   *Edwar Oswaldo Diaz Garzón*

# **Objetivo**

Conocer la cantidad de personas que tienen acceso a internet

# ***Se importan las libreria***
Para conocer la informacion de nuestro dataframe y lograr responder la preguntar

importamos las librerias necesarias, nuestro datraframe fue sacado de la pagina oficial de dane.


https://www.dane.gov.co/index.php/estadisticas-por-tema/cultura/consumo-cultural


Mostramos la primera tabla que es la de los totales.
"""

import pandas as pd
import glob
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('/content/01.xls (1).xlsx')
df.head()

"""# **Se muestran el numero de columnas y filas**

Para conocer mas nuestro dataframe buscamos en numero de filas y columnas.
"""

df.shape
#(24707, 13)

"""#Mostramos la tabla

Mostramos la tabla de otra manera para conocer, si se omite algun tipo de dato

"""

df.head()

"""#**Se muestra la primera fila del archivo**

Para identificar y mirar las posiciones de los valores totales de hombres y mujeres entre las edades de 5 a 11 años

Con esta informacion procedemos a crear las debidas graficas para responder la pregunta inicial.

"""

df=df.rename(columns={'Uso de internet': 'Total','hombres':'mujeres'})
df.head(1)

"""#Declarar

Se declaran 4 variables con las cuales se realizaran las debidas graficas
"""

valor1 = df.iloc[1, 4]  # Fila 0, columna 4 (Hombres)
valor2 = df.iloc[1, 6]  # Fila 0, columna 6 (Mujeres)
valor3 = df.iloc[4, 4]  # Fila 0, columna 6 (Mujeres)
valor4 = df.iloc[4, 6]  # Fila 0, columna 6 (Mujeres)

print(valor1, valor2, valor3, valor4)

"""#Se hace las graficas  

Con los valores recolectados se hacen las debidas graficas

usamos la libreria matplotlib.pyplot para hacer las graficas

hacemos una grafica de pastel donde tenemos los porcentajes
"""

import matplotlib.pyplot as plt

# Guardar los valores seleccionados en una lista
valores = [valor1, valor2]
etiquetas = ['Hombres', 'Mujeres']

# Crear el gráfico de torta
plt.pie(valores, labels=etiquetas, autopct='%1.1f%%', startangle=90)

# Asegurar que el gráfico sea circular
plt.axis('equal')

plt.title('Totales de Hombres y Mujeres encuestadas')
# Mostrar el gráfico
plt.show()

"""## Se muestra la grafica de barras

En esta grafica mostramos las mujeres con acceso, sin acceso, hombres con acceso, y sin acceso
"""

# Guardar los valores seleccionados en una lista
valores = [valor1, valor2, valor3, valor4]
etiquetas = ['Hombres con', 'Hombres sin', 'mujeres con', 'mujeres sin']

# Crear el gráfico de barras
plt.bar(etiquetas, valores, color=['blue', 'red', 'black', 'green'])

# Agregar etiquetas y título
plt.xlabel('Categorías')
plt.ylabel('Valores')
plt.title('Distribución de encuestados con y sin internet')

# Mostrar el gráfico
plt.show()

"""#Conclusion

Se evidencio el dominio de las personas con acceso a internet, demostrando que son mas las personas que cuentan con internet, que las que no.
"""